---
driver:
  name: podman
platforms:
  - name: rockylinux9
    image: rockylinux:9
    command: /bin/sh -c "while true; do sleep 3600; done"
    privileged: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
